export const countries = [
    { name: "Afghanistan", phone_code: "+93", flag: "https://flagcdn.com/w40/af.png", cca2: "AF" },
    { name: "Albania", phone_code: "+355", flag: "https://flagcdn.com/w40/al.png", cca2: "AL" },
    { name: "Algeria", phone_code: "+213", flag: "https://flagcdn.com/w40/dz.png", cca2: "DZ" },
    { name: "Andorra", phone_code: "+376", flag: "https://flagcdn.com/w40/ad.png", cca2: "AD" },
    { name: "Angola", phone_code: "+244", flag: "https://flagcdn.com/w40/ao.png", cca2: "AO" },
    { name: "Argentina", phone_code: "+54", flag: "https://flagcdn.com/w40/ar.png", cca2: "AR" },
    { name: "Armenia", phone_code: "+374", flag: "https://flagcdn.com/w40/am.png", cca2: "AM" },
    { name: "Australia", phone_code: "+61", flag: "https://flagcdn.com/w40/au.png", cca2: "AU" },
    { name: "Austria", phone_code: "+43", flag: "https://flagcdn.com/w40/at.png", cca2: "AT" },
    { name: "Azerbaijan", phone_code: "+994", flag: "https://flagcdn.com/w40/az.png", cca2: "AZ" },
    { name: "Bahamas", phone_code: "+1242", flag: "https://flagcdn.com/w40/bs.png", cca2: "BS" },
    { name: "Bahrain", phone_code: "+973", flag: "https://flagcdn.com/w40/bh.png", cca2: "BH" },
    { name: "Bangladesh", phone_code: "+880", flag: "https://flagcdn.com/w40/bd.png", cca2: "BD" },
    { name: "Barbados", phone_code: "+1246", flag: "https://flagcdn.com/w40/bb.png", cca2: "BB" },
    { name: "Belarus", phone_code: "+375", flag: "https://flagcdn.com/w40/by.png", cca2: "BY" },
    { name: "Belgium", phone_code: "+32", flag: "https://flagcdn.com/w40/be.png", cca2: "BE" },
    { name: "Belize", phone_code: "+501", flag: "https://flagcdn.com/w40/bz.png", cca2: "BZ" },
    { name: "Benin", phone_code: "+229", flag: "https://flagcdn.com/w40/bj.png", cca2: "BJ" },
    { name: "Bhutan", phone_code: "+975", flag: "https://flagcdn.com/w40/bt.png", cca2: "BT" },
    { name: "Bolivia", phone_code: "+591", flag: "https://flagcdn.com/w40/bo.png", cca2: "BO" },
    { name: "Bosnia and Herzegovina", phone_code: "+387", flag: "https://flagcdn.com/w40/ba.png", cca2: "BA" },
    { name: "Botswana", phone_code: "+267", flag: "https://flagcdn.com/w40/bw.png", cca2: "BW" },
    { name: "Brazil", phone_code: "+55", flag: "https://flagcdn.com/w40/br.png", cca2: "BR" },
    { name: "Brunei", phone_code: "+673", flag: "https://flagcdn.com/w40/bn.png", cca2: "BN" },
    { name: "Bulgaria", phone_code: "+359", flag: "https://flagcdn.com/w40/bg.png", cca2: "BG" },
    { name: "Burkina Faso", phone_code: "+226", flag: "https://flagcdn.com/w40/bf.png", cca2: "BF" },
    { name: "Burundi", phone_code: "+257", flag: "https://flagcdn.com/w40/bi.png", cca2: "BI" },
    { name: "Cambodia", phone_code: "+855", flag: "https://flagcdn.com/w40/kh.png", cca2: "KH" },
    { name: "Cameroon", phone_code: "+237", flag: "https://flagcdn.com/w40/cm.png", cca2: "CM" },
    { name: "Canada", phone_code: "+1", flag: "https://flagcdn.com/w40/ca.png", cca2: "CA" },
    { name: "Cape Verde", phone_code: "+238", flag: "https://flagcdn.com/w40/cv.png", cca2: "CV" },
    { name: "Central African Republic", phone_code: "+236", flag: "https://flagcdn.com/w40/cf.png", cca2: "CF" },
    { name: "Chad", phone_code: "+235", flag: "https://flagcdn.com/w40/td.png", cca2: "TD" },
    { name: "Chile", phone_code: "+56", flag: "https://flagcdn.com/w40/cl.png", cca2: "CL" },
    { name: "China", phone_code: "+86", flag: "https://flagcdn.com/w40/cn.png", cca2: "CN" },
    { name: "Colombia", phone_code: "+57", flag: "https://flagcdn.com/w40/co.png", cca2: "CO" },
    { name: "Comoros", phone_code: "+269", flag: "https://flagcdn.com/w40/km.png", cca2: "KM" },
    { name: "Costa Rica", phone_code: "+506", flag: "https://flagcdn.com/w40/cr.png", cca2: "CR" },
    { name: "Croatia", phone_code: "+385", flag: "https://flagcdn.com/w40/hr.png", cca2: "HR" },
    { name: "Cuba", phone_code: "+53", flag: "https://flagcdn.com/w40/cu.png", cca2: "CU" },
    { name: "Cyprus", phone_code: "+357", flag: "https://flagcdn.com/w40/cy.png", cca2: "CY" },
    { name: "Czechia", phone_code: "+420", flag: "https://flagcdn.com/w40/cz.png", cca2: "CZ" },
    { name: "Denmark", phone_code: "+45", flag: "https://flagcdn.com/w40/dk.png", cca2: "DK" },
    { name: "Djibouti", phone_code: "+253", flag: "https://flagcdn.com/w40/dj.png", cca2: "DJ" },
    { name: "Dominica", phone_code: "+1767", flag: "https://flagcdn.com/w40/dm.png", cca2: "DM" },
    { name: "Dominican Republic", phone_code: "+1809", flag: "https://flagcdn.com/w40/do.png", cca2: "DO" },
    { name: "Ecuador", phone_code: "+593", flag: "https://flagcdn.com/w40/ec.png", cca2: "EC" },
    { name: "Egypt", phone_code: "+20", flag: "https://flagcdn.com/w40/eg.png", cca2: "EG" },
    { name: "El Salvador", phone_code: "+503", flag: "https://flagcdn.com/w40/sv.png", cca2: "SV" },
    { name: "Equatorial Guinea", phone_code: "+240", flag: "https://flagcdn.com/w40/gq.png", cca2: "GQ" },
    { name: "Eritrea", phone_code: "+291", flag: "https://flagcdn.com/w40/er.png", cca2: "ER" },
    { name: "Estonia", phone_code: "+372", flag: "https://flagcdn.com/w40/ee.png", cca2: "EE" },
    { name: "Eswatini", phone_code: "+268", flag: "https://flagcdn.com/w40/sz.png", cca2: "SZ" },
    { name: "Ethiopia", phone_code: "+251", flag: "https://flagcdn.com/w40/et.png", cca2: "ET" },
    { name: "Fiji", phone_code: "+679", flag: "https://flagcdn.com/w40/fj.png", cca2: "FJ" },
    { name: "Finland", phone_code: "+358", flag: "https://flagcdn.com/w40/fi.png", cca2: "FI" },
    { name: "France", phone_code: "+33", flag: "https://flagcdn.com/w40/fr.png", cca2: "FR" },
    { name: "Gabon", phone_code: "+241", flag: "https://flagcdn.com/w40/ga.png", cca2: "GA" },
    { name: "Gambia", phone_code: "+220", flag: "https://flagcdn.com/w40/gm.png", cca2: "GM" },
    { name: "Georgia", phone_code: "+995", flag: "https://flagcdn.com/w40/ge.png", cca2: "GE" },
    { name: "Germany", phone_code: "+49", flag: "https://flagcdn.com/w40/de.png", cca2: "DE" },
    { name: "Ghana", phone_code: "+233", flag: "https://flagcdn.com/w40/gh.png", cca2: "GH" },
    { name: "Greece", phone_code: "+30", flag: "https://flagcdn.com/w40/gr.png", cca2: "GR" },
    { name: "Grenada", phone_code: "+1473", flag: "https://flagcdn.com/w40/gd.png", cca2: "GD" },
    { name: "Guatemala", phone_code: "+502", flag: "https://flagcdn.com/w40/gt.png", cca2: "GT" },
    { name: "Guinea", phone_code: "+224", flag: "https://flagcdn.com/w40/gn.png", cca2: "GN" },
    { name: "Guinea-Bissau", phone_code: "+245", flag: "https://flagcdn.com/w40/gw.png", cca2: "GW" },
    { name: "Guyana", phone_code: "+592", flag: "https://flagcdn.com/w40/gy.png", cca2: "GY" },
    { name: "Haiti", phone_code: "+509", flag: "https://flagcdn.com/w40/ht.png", cca2: "HT" },
    { name: "Honduras", phone_code: "+504", flag: "https://flagcdn.com/w40/hn.png", cca2: "HN" },
    { name: "Hungary", phone_code: "+36", flag: "https://flagcdn.com/w40/hu.png", cca2: "HU" },
    { name: "Iceland", phone_code: "+354", flag: "https://flagcdn.com/w40/is.png", cca2: "IS" },
    { name: "India", phone_code: "+91", flag: "https://flagcdn.com/w40/in.png", cca2: "IN" },
    { name: "Indonesia", phone_code: "+62", flag: "https://flagcdn.com/w40/id.png", cca2: "ID" },
    { name: "Iran", phone_code: "+98", flag: "https://flagcdn.com/w40/ir.png", cca2: "IR" },
    { name: "Iraq", phone_code: "+964", flag: "https://flagcdn.com/w40/iq.png", cca2: "IQ" },
    { name: "Ireland", phone_code: "+353", flag: "https://flagcdn.com/w40/ie.png", cca2: "IE" },
    { name: "Israel", phone_code: "+972", flag: "https://flagcdn.com/w40/il.png", cca2: "IL" },
    { name: "Italy", phone_code: "+39", flag: "https://flagcdn.com/w40/it.png", cca2: "IT" },
    { name: "Jamaica", phone_code: "+1876", flag: "https://flagcdn.com/w40/jm.png", cca2: "JM" },
    { name: "Japan", phone_code: "+81", flag: "https://flagcdn.com/w40/jp.png", cca2: "JP" },
    { name: "Jordan", phone_code: "+962", flag: "https://flagcdn.com/w40/jo.png", cca2: "JO" },
    { name: "Kazakhstan", phone_code: "+7", flag: "https://flagcdn.com/w40/kz.png", cca2: "KZ" },
    { name: "Kenya", phone_code: "+254", flag: "https://flagcdn.com/w40/ke.png", cca2: "KE" },
    { name: "Kiribati", phone_code: "+686", flag: "https://flagcdn.com/w40/ki.png", cca2: "KI" },
    { name: "Kuwait", phone_code: "+965", flag: "https://flagcdn.com/w40/kw.png", cca2: "KW" },
    { name: "Kyrgyzstan", phone_code: "+996", flag: "https://flagcdn.com/w40/kg.png", cca2: "KG" },
    { name: "Laos", phone_code: "+856", flag: "https://flagcdn.com/w40/la.png", cca2: "LA" },
    { name: "Latvia", phone_code: "+371", flag: "https://flagcdn.com/w40/lv.png", cca2: "LV" },
    { name: "Lebanon", phone_code: "+961", flag: "https://flagcdn.com/w40/lb.png", cca2: "LB" },
    { name: "Lesotho", phone_code: "+266", flag: "https://flagcdn.com/w40/ls.png", cca2: "LS" },
    { name: "Liberia", phone_code: "+231", flag: "https://flagcdn.com/w40/lr.png", cca2: "LR" },
    { name: "Libya", phone_code: "+218", flag: "https://flagcdn.com/w40/ly.png", cca2: "LY" },
    { name: "Liechtenstein", phone_code: "+423", flag: "https://flagcdn.com/w40/li.png", cca2: "LI" },
    { name: "Lithuania", phone_code: "+370", flag: "https://flagcdn.com/w40/lt.png", cca2: "LT" },
    { name: "Luxembourg", phone_code: "+352", flag: "https://flagcdn.com/w40/lu.png", cca2: "LU" },
    { name: "Madagascar", phone_code: "+261", flag: "https://flagcdn.com/w40/mg.png", cca2: "MG" },
    { name: "Malawi", phone_code: "+265", flag: "https://flagcdn.com/w40/mw.png", cca2: "MW" },
    { name: "Malaysia", phone_code: "+60", flag: "https://flagcdn.com/w40/my.png", cca2: "MY" },
    { name: "Maldives", phone_code: "+960", flag: "https://flagcdn.com/w40/mv.png", cca2: "MV" },
    { name: "Mali", phone_code: "+223", flag: "https://flagcdn.com/w40/ml.png", cca2: "ML" },
    { name: "Malta", phone_code: "+356", flag: "https://flagcdn.com/w40/mt.png", cca2: "MT" },
    { name: "Marshall Islands", phone_code: "+692", flag: "https://flagcdn.com/w40/mh.png", cca2: "MH" },
    { name: "Mauritania", phone_code: "+222", flag: "https://flagcdn.com/w40/mr.png", cca2: "MR" },
    { name: "Mauritius", phone_code: "+230", flag: "https://flagcdn.com/w40/mu.png", cca2: "MU" },
    { name: "Mexico", phone_code: "+52", flag: "https://flagcdn.com/w40/mx.png", cca2: "MX" },
    { name: "Micronesia", phone_code: "+691", flag: "https://flagcdn.com/w40/fm.png", cca2: "FM" },
    { name: "Moldova", phone_code: "+373", flag: "https://flagcdn.com/w40/md.png", cca2: "MD" },
    { name: "Monaco", phone_code: "+377", flag: "https://flagcdn.com/w40/mc.png", cca2: "MC" },
    { name: "Mongolia", phone_code: "+976", flag: "https://flagcdn.com/w40/mn.png", cca2: "MN" },
    { name: "Montenegro", phone_code: "+382", flag: "https://flagcdn.com/w40/me.png", cca2: "ME" },
    { name: "Morocco", phone_code: "+212", flag: "https://flagcdn.com/w40/ma.png", cca2: "MA" },
    { name: "Mozambique", phone_code: "+258", flag: "https://flagcdn.com/w40/mz.png", cca2: "MZ" },
    { name: "Myanmar", phone_code: "+95", flag: "https://flagcdn.com/w40/mm.png", cca2: "MM" },
    { name: "Namibia", phone_code: "+264", flag: "https://flagcdn.com/w40/na.png", cca2: "NA" },
    { name: "Nauru", phone_code: "+674", flag: "https://flagcdn.com/w40/nr.png", cca2: "NR" },
    { name: "Nepal", phone_code: "+977", flag: "https://flagcdn.com/w40/np.png", cca2: "NP" },
    { name: "Netherlands", phone_code: "+31", flag: "https://flagcdn.com/w40/nl.png", cca2: "NL" },
    { name: "New Zealand", phone_code: "+64", flag: "https://flagcdn.com/w40/nz.png", cca2: "NZ" },
    { name: "Nicaragua", phone_code: "+505", flag: "https://flagcdn.com/w40/ni.png", cca2: "NI" },
    { name: "Niger", phone_code: "+227", flag: "https://flagcdn.com/w40/ne.png", cca2: "NE" },
    { name: "Nigeria", phone_code: "+234", flag: "https://flagcdn.com/w40/ng.png", cca2: "NG" },
    { name: "Norway", phone_code: "+47", flag: "https://flagcdn.com/w40/no.png", cca2: "NO" },
    { name: "Oman", phone_code: "+968", flag: "https://flagcdn.com/w40/om.png", cca2: "OM" },
    { name: "Pakistan", phone_code: "+92", flag: "https://flagcdn.com/w40/pk.png", cca2: "PK" },
    { name: "Palau", phone_code: "+680", flag: "https://flagcdn.com/w40/pw.png", cca2: "PW" },
    { name: "Panama", phone_code: "+507", flag: "https://flagcdn.com/w40/pa.png", cca2: "PA" },
    { name: "Papua New Guinea", phone_code: "+675", flag: "https://flagcdn.com/w40/pg.png", cca2: "PG" },
    { name: "Paraguay", phone_code: "+595", flag: "https://flagcdn.com/w40/py.png", cca2: "PY" },
    { name: "Peru", phone_code: "+51", flag: "https://flagcdn.com/w40/pe.png", cca2: "PE" },
    { name: "Philippines", phone_code: "+63", flag: "https://flagcdn.com/w40/ph.png", cca2: "PH" },
    { name: "Poland", phone_code: "+48", flag: "https://flagcdn.com/w40/pl.png", cca2: "PL" },
    { name: "Portugal", phone_code: "+351", flag: "https://flagcdn.com/w40/pt.png", cca2: "PT" },
    { name: "Qatar", phone_code: "+974", flag: "https://flagcdn.com/w40/qa.png", cca2: "QA" },
    { name: "Romania", phone_code: "+40", flag: "https://flagcdn.com/w40/ro.png", cca2: "RO" },
    { name: "Russia", phone_code: "+7", flag: "https://flagcdn.com/w40/ru.png", cca2: "RU" },
    { name: "Rwanda", phone_code: "+250", flag: "https://flagcdn.com/w40/rw.png", cca2: "RW" },
    { name: "Saint Kitts and Nevis", phone_code: "+1869", flag: "https://flagcdn.com/w40/kn.png", cca2: "KN" },
    { name: "Saint Lucia", phone_code: "+1758", flag: "https://flagcdn.com/w40/lc.png", cca2: "LC" },
    { name: "Saint Vincent and the Grenadines", phone_code: "+1784", flag: "https://flagcdn.com/w40/vc.png", cca2: "VC" },
    { name: "Samoa", phone_code: "+685", flag: "https://flagcdn.com/w40/ws.png", cca2: "WS" },
    { name: "San Marino", phone_code: "+378", flag: "https://flagcdn.com/w40/sm.png", cca2: "SM" },
    { name: "Sao Tome and Principe", phone_code: "+239", flag: "https://flagcdn.com/w40/st.png", cca2: "ST" },
    { name: "Saudi Arabia", phone_code: "+966", flag: "https://flagcdn.com/w40/sa.png", cca2: "SA" },
    { name: "Senegal", phone_code: "+221", flag: "https://flagcdn.com/w40/sn.png", cca2: "SN" },
    { name: "Serbia", phone_code: "+381", flag: "https://flagcdn.com/w40/rs.png", cca2: "RS" },
    { name: "Seychelles", phone_code: "+248", flag: "https://flagcdn.com/w40/sc.png", cca2: "SC" },
    { name: "Sierra Leone", phone_code: "+232", flag: "https://flagcdn.com/w40/sl.png", cca2: "SL" },
    { name: "Singapore", phone_code: "+65", flag: "https://flagcdn.com/w40/sg.png", cca2: "SG" },
    { name: "Slovakia", phone_code: "+421", flag: "https://flagcdn.com/w40/sk.png", cca2: "SK" },
    { name: "Slovenia", phone_code: "+386", flag: "https://flagcdn.com/w40/si.png", cca2: "SI" },
    { name: "Solomon Islands", phone_code: "+677", flag: "https://flagcdn.com/w40/sb.png", cca2: "SB" },
    { name: "Somalia", phone_code: "+252", flag: "https://flagcdn.com/w40/so.png", cca2: "SO" },
    { name: "South Africa", phone_code: "+27", flag: "https://flagcdn.com/w40/za.png", cca2: "ZA" },
    { name: "South Korea", phone_code: "+82", flag: "https://flagcdn.com/w40/kr.png", cca2: "KR" },
    { name: "Spain", phone_code: "+34", flag: "https://flagcdn.com/w40/es.png", cca2: "ES" },
    { name: "Sri Lanka", phone_code: "+94", flag: "https://flagcdn.com/w40/lk.png", cca2: "LK" },
    { name: "Sudan", phone_code: "+249", flag: "https://flagcdn.com/w40/sd.png", cca2: "SD" },
    { name: "Suriname", phone_code: "+597", flag: "https://flagcdn.com/w40/sr.png", cca2: "SR" },
    { name: "Sweden", phone_code: "+46", flag: "https://flagcdn.com/w40/se.png", cca2: "SE" },
    { name: "Switzerland", phone_code: "+41", flag: "https://flagcdn.com/w40/ch.png", cca2: "CH" },
    { name: "Syria", phone_code: "+963", flag: "https://flagcdn.com/w40/sy.png", cca2: "SY" },
    { name: "Taiwan", phone_code: "+886", flag: "https://flagcdn.com/w40/tw.png", cca2: "TW" },
    { name: "Tajikistan", phone_code: "+992", flag: "https://flagcdn.com/w40/tj.png", cca2: "TJ" },
    { name: "Tanzania", phone_code: "+255", flag: "https://flagcdn.com/w40/tz.png", cca2: "TZ" },
    { name: "Thailand", phone_code: "+66", flag: "https://flagcdn.com/w40/th.png", cca2: "TH" },
    { name: "Togo", phone_code: "+228", flag: "https://flagcdn.com/w40/tg.png", cca2: "TG" },
    { name: "Tonga", phone_code: "+676", flag: "https://flagcdn.com/w40/to.png", cca2: "TO" },
    { name: "Trinidad and Tobago", phone_code: "+1868", flag: "https://flagcdn.com/w40/tt.png", cca2: "TT" },
    { name: "Tunisia", phone_code: "+216", flag: "https://flagcdn.com/w40/tn.png", cca2: "TN" },
    { name: "Turkey", phone_code: "+90", flag: "https://flagcdn.com/w40/tr.png", cca2: "TR" },
    { name: "Turkmenistan", phone_code: "+993", flag: "https://flagcdn.com/w40/tm.png", cca2: "TM" },
    { name: "Tuvalu", phone_code: "+688", flag: "https://flagcdn.com/w40/tv.png", cca2: "TV" },
    { name: "Uganda", phone_code: "+256", flag: "https://flagcdn.com/w40/ug.png", cca2: "UG" },
    { name: "Ukraine", phone_code: "+380", flag: "https://flagcdn.com/w40/ua.png", cca2: "UA" },
    { name: "United Arab Emirates", phone_code: "+971", flag: "https://flagcdn.com/w40/ae.png", cca2: "AE" },
    { name: "United Kingdom", phone_code: "+44", flag: "https://flagcdn.com/w40/gb.png", cca2: "GB" },
    { name: "United States", phone_code: "+1", flag: "https://flagcdn.com/w40/us.png", cca2: "US" },
    { name: "Uruguay", phone_code: "+598", flag: "https://flagcdn.com/w40/uy.png", cca2: "UY" },
    { name: "Uzbekistan", phone_code: "+998", flag: "https://flagcdn.com/w40/uz.png", cca2: "UZ" },
    { name: "Vanuatu", phone_code: "+678", flag: "https://flagcdn.com/w40/vu.png", cca2: "VU" },
    { name: "Venezuela", phone_code: "+58", flag: "https://flagcdn.com/w40/ve.png", cca2: "VE" },
    { name: "Vietnam", phone_code: "+84", flag: "https://flagcdn.com/w40/vn.png", cca2: "VN" },
    { name: "Yemen", phone_code: "+967", flag: "https://flagcdn.com/w40/ye.png", cca2: "YE" },
    { name: "Zambia", phone_code: "+260", flag: "https://flagcdn.com/w40/zm.png", cca2: "ZM" },
    { name: "Zimbabwe", phone_code: "+263", flag: "https://flagcdn.com/w40/zw.png", cca2: "ZW" }
];
